### PR TITLE
Apply latest figma updates (30.09)

### PR DESCRIPTION
**Pull request by kh-ruslan**

### CODE REVIEW

**Comment by josadcha** [comment]
Illustation has poor quality. Have you exported them with 2x option? 
Something bad happen to this illustration. It became thinner
image

**Comment by kh-ruslan** [comment]
> Illustation has poor quality. Have you exported them with 2x option? Something bad happen to this illustration. It became thinner image

let me try 2x

**Review by plsthink — APPROVED** [review]
Very nice work!

**Comment by kh-ruslan** [comment]
> let me try 2x

@josadcha  Unfortunately 2x is even worse, it adds some kind of blur to the image. I've exported the image in svg format, it became a bit better, please check again.

**Review by josadcha — APPROVED** [review]
looks great

**Pull request merged**
