### PR TITLE
Fix links styling

### LINKED ISSUE #55: Index page buttons shadow issue
Buttons "shadows" on index page sections (except Hero) have incorrect styling.

a

### PR DESCRIPTION
**Pull request by plsthink**
Fixes #55

### CODE REVIEW

**Review by josadcha — CHANGES_REQUESTED** [review]
Please cover also cases
- when link is image as in blog post: https://yellow-org-git-fix-links-style-openware.vercel.app/blog
- when link is tag 
- when link is anchor element on docs page 
image

image

**Comment by plsthink** [comment]
@josadcha Done

**Comment by kh-ruslan** [comment]
It adds extra spaces to the site, probably cause it shows a link that was hidden before the changes:
image

**Comment by plsthink** [comment]
> It adds extra spaces to the site, probably cause it shows a link that was hidden before the changes:
> image

fixed

**Comment by kh-ruslan** [comment]
@josadcha @lckmidnight is it okay that it adds yellow underline animation on hover to all these link types?
image
image
image
image

And it also **removes** black underline animation from navbar:
image

**Comment by josadcha** [comment]
> @josadcha @lckmidnight is it okay that it adds yellow underline animation on hover to all these link types?
> image
> image
> image
> image
> 
> And it also **removes** black underline animation from navbar:
> image

it should add underline for links inside text, but not for button 'next page' of course

**Comment by plsthink** [comment]
Updated.
The only thing remaining is the links on icons, but since they have no class, i can not filter them out.
But this looks good, so maybe not an issue?

**Review by josadcha — APPROVED** [review]

**Pull request merged**
